name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main
  # Task 1: Add a manual workflow trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Task 2: Add a step to run the unit test
      - name: Run unit tests
        run: |
          python -m pytest tests
        env:
          PYTHONPATH: .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Task 3: Use the GitHub secret for service account JSON key
          credentials_json: ${{ secrets.GAE_SA_KEY }}

      - name: Ensure App Engine is initialized
        run: |
          gcloud app describe --project ${{ secrets.GCP_PROJECT_ID }} || \
          gcloud app create --project ${{ secrets.GCP_PROJECT_ID }} --region=us-central

      - name: Deploy to App Engine
        run: |
          # Task 4: Ensure gcloud app engine is set up and deploy
          gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --quiet

      - name: Ensure App Engine is ready (Step 4)
        run: |
          # Wait for App Engine service to stabilize
          gcloud app describe --project ${{ secrets.GCP_PROJECT_ID }}
